# Generated by Django 5.0.3 on 2024-05-19 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioinformaticsTool',
            fields=[
                ('tool_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='ToolID must start with tl followed by 3 digits', regex='^tl\\d{3}$')])),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_description', models.TextField(blank=True)),
                ('tool_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('sample_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='SampleID must start with sp followed by 3 digits', regex='^sp\\d{3}$')])),
                ('sample_name', models.CharField(max_length=255)),
                ('sample_type', models.CharField(max_length=255)),
                ('diagnosis_group', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='StatusID must start with st followed by 3 digits', regex='^st\\d{3}$')])),
                ('status_name', models.CharField(max_length=255)),
                ('status_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('data_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='DataID must start with ud followed by 3 digits', regex='^ud\\d{3}$')])),
                ('data', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='HistoryID must start with ht followed by 3 digits', regex='^ht\\d{3}$')])),
                ('history_name', models.CharField(max_length=255)),
                ('process_file_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bioinformaticstool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uploaddata')),
            ],
        ),
    ]
