# Generated by Django 5.0.3 on 2024-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticstool',
            name='package_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
