# Generated by Django 5.0.3 on 2024-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bioinformaticstool_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticstool',
            name='tool_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
