# Generated by Django 5.0.3 on 2024-05-25 17:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bioinformaticstool_tool_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='HistoryID must start with ht followed by 3 digits', regex='^ht\\d{3}$')])),
                ('history_name', models.CharField(max_length=255)),
                ('input_data_path', models.TextField(blank=True)),
                ('process_file_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bioinformaticstool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
