# Generated by Django 5.0.3 on 2024-05-26 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('sample_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='SampleID must start with sp followed by 3 digits', regex='^sp\\d{3}$')])),
                ('sample_name', models.CharField(max_length=255)),
                ('sample_type', models.CharField(max_length=255)),
                ('diagnosis_group', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
