# Generated by Django 5.0.3 on 2024-05-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.history'),
        ),
    ]
